### ISSUE TITLE
link styling 

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#171]
links in the PDF don't show with an underline or any other styling (though they are functional). Example from Ch6:

<img width="579" alt="Screenshot 2023-06-21 at 10 18 14 AM" src="https://github.com/langcog/experimentology/assets/1158807/2fd52f86-0783-4ad2-924f-00ea08a55e64">

**Comment by mikabr** [comment]
this isn't just an styling issue -- a link like this is fine in the pdf but will be unusable when printed...

**Comment by mikabr** [comment]
here's a potential solution that turns links into footnotes (from https://bookdown.org/yihui/bookdown/publishers.html)

<img width="480" alt="Screen Shot 2023-06-28 at 6 26 57 PM" src="https://github.com/langcog/experimentology/assets/1414971/9099c16c-f42f-470d-b6a7-36b5525f775f">

**Comment by mcfrank** [comment]
That’s very style consistent!!
-- 
Mike

**Comment by mikabr** [comment]
turns out the strategy of putting urls into sidenotes has the issue that it doesn't work when the link itself is already in a sidenote (you can't have nested sidenotes)

an alternative could be to put the urls into footnotes, as done [here](https://tex.stackexchange.com/questions/449073/parallel-footnote-and-sidenote-environments-with-nested-references)

**Comment by mcfrank** [comment]
got it, I'm fine with that.
