### ISSUE TITLE
Preregistration

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#33]
Some todos for the next revision:

- [x] Figure out what kind of boxes we actually want to have here. 
- [x] Think through what the right case study is and add it back in (for me to do, probably)?
- [x] Barriers to adoption of preregistration.
- [ ] Limitations of the preregistration approach, especially with respect to iterative theory building (e.g., Navarro critique). 
- [ ] Components of a preregistration - sample size/sampling strategy, analysis, exclusions, etc.? can we enumerate these more explicitly?

**Comment by kateptrv** [comment]
Terrific chapter! Some suggestions:

- It would be great to devote just a little bit of space in the chapter to a discussion of how preregistration can be useful at different stages in the research process as well as in non-experimental research. This may be particularly important to add considering that a large chunk of the target audience are ECRs. Many undergrad/grad students, postbacs, and postdocs join existing projects with data that have already been collected, but they still can (and, I would argue, many of them should) preregister their hypotheses and analysis plans. 
- I also think the chapter would benefit from a more nuanced discussion of the exploratory-confirmatory spectrum. (Perhaps something along the lines of this piece in the American Psychologist: https://psyarxiv.com/5vfq6/ )
- A more general suggestion is to consider framing the chapter around the "carrots" of open science -- the benefits of preregistration _to the researcher_ . The way it's set up now all about avoiding the dangers of forking paths/preventing oneself from falling into the traps of one's own biases (both of which are presented _extremely_ effectively, btw!). One thought is to set up the stage for the discussion of forking paths by prompting the reader to think about what they _want_ their research journey to look like. Most readers will say that they want their work to be rigorous, trustworthy, well-designed, and free of biases. Most will also agree that they want their workflow to be organized, efficient, and free of errors and miscommunications with co-authors. Once the common ground is established, the readers will want to know how to make their ideal research program/workflow a reality, and the rest of the chapter will provide answers to exactly those kinds of questions!

**Comment by TomHardwicke** [comment]
That's terrific feedback, thanks Kate. I'll incorporate into the next draft. I'd slightly push back on your third point only in the sense that I think often methodological recommendations like preregistration, data sharing etc, are primarily motivated/justified by their extrinsic benefits to the scientific ecosystem, rather than an intrinsic cost/benefit analysis at the level of individual researchers. I worry that its a bit misleading and even potentially counter-productive to frame these practices equally in terms of auxiliary personal benefits, because that may lead to suboptimal implementation and understanding. But I do agree with you that there are potential personal benefits (at least in my experience) and we can do a better job of highlighting those - I like you're idea of getting the reader to think about an overall vision of what they want their research to look like right from the start of the chapter. I'd be interested to hear any further your thoughts you have, either in response to that or after I've made some changes. Cheers!
