### ISSUE TITLE
viz chapter feedback

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#48]
@hawkrobe - love the viz chapter, but I did want to suggest that we might look for a few more psych examples (e.g. rather than covid or iris). 

for iris could we use a personality dataset, e.g. something on big 5 personality measures? @JYAC any thoughts? 

for time course, could we use eye-tracking and word recognition? e.g., something like tanenhaus classic anticipation?

**Comment by hawkrobe** [comment]
this is a great idea! in line with the themes, I wonder whether we could data from a big replication, like [this](https://openpsychologydata.metajnl.com/articles/10.5334/jopd.ai/) replication of Shepard & Metzler mental rotation? or [this one](https://openpsychologydata.metajnl.com/articles/10.5334/jopd.ak/) with the iowa gambling task instead of a more observational personality dataset? 

and 100% agreed a tanenhaus eyetracking experiment would be great to swap in for the covid example. do you know of a good open dataset from a visual world paradigm? 

also, just came across [this](https://cims.nyu.edu/~brenden/courses/labincp/chapters/06/00-plots.html) chapter when googling around and might be nice to acknowledge as an existing resource?
