### ISSUE TITLE
measurement theory

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#65]
@hawkrobe can add a box that discusses some of the history of measurement theory (e.g., estes, suppes, tversky) and how to measure reaction times well...

**Comment by mcfrank** [comment]
good candidate for a `depth` box.

**Comment by hawkrobe** [comment]
collecting some thoughts from reviewing the measurement chapter here! 

* I got confused very quickly in the intro about what it means to 'make a measurement' of a latent construct or causal effect. In the literature that I'm familiar with, we usually talk about 'making an *inference*' about a latent construct or causal effect **conditioned on** measurable observations. In other words, 'measurement' is usually reserved for the raw numbers recorded by our instruments, not the inference itself (e.g. in physics, wavelengths of light go into a spectrometer and the measurements are spectrometer readings; in biology, neuron activity goes into a patch clamp and the measurements are the voltage readings; in both cases, you can use those measurements to make inferences about the underlying thing of interest, but you can't directly take a measurement *of* the underlying thing.) Maybe this is too nit-picky about terminology, but I'd like to be a bit more careful about slippage.

* We use IQ uncritically as an example in several places. Maybe this is a good place for an ethics box discussing why IQ is considered problematic as a measure of intelligence? (and racist misuses such as 'national IQ'?) Generally, I think this chapter is a good place to discuss 'phrenology' style arguments: roughly, just because you *can* measure something (like skull shapes) doesn't mean it's scientifically meaningful. Lots of pseudo-science works by appealing to the apparent rigor of measurement. 

* I wonder whether 8.3.1 (What to measure?) could be broken into a few different subsections (simplicity vs. complexity and implicit vs. explicit?), and whether 8.3.2 (Survey measures) could be moved to a depth box? 

I will come back to this tomorrow and add more thoughts!

**Comment by mcfrank** [comment]
- remove footnote 1
- "The difference is that in psychology, we are typically trying to measure constructs – invented theoretical entities located inside people’s heads!" - check this talk
- **estimate** a causal effect using **measurements** - the effects ($\hat{beta}$) are hopefully related to the theoretical causal relationship of interest ($\beta$).
- 
![Screen Shot 2022-09-15 at 3 45 21 PM](https://user-images.githubusercontent.com/1158807/190521559-8278d1d1-0560-4153-8c47-70311397364b.png)
