### ISSUE TITLE
syllabus buttons in instructor guide don't work

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#87]
these seem really cool but unfortunately they are broken in the current build (@mikabr @JYAC)

**Comment by mcfrank** [comment]
Maybe it has to do with bootstrap not being used here. I moved to tables and tried doing panelset from xaringanExtra but that also didn’t work.

**Comment by mcfrank** [comment]
perhaps this is about specifying that we need bootstrap4? in any case I turned them into tables for now.

**Comment by JYAC** [comment]
Yes, sorry about this @mcfrank! I really struggled with making bs4cards work - at first I thought it was because we hadn't enabled boostrap4 (as suggested [here](https://bs4cards.djnavarro.net/articles/articles/enabling-bootstrap4.html)), but couldn't figure out how to enable it. I think turning them into tables for now makes total sense, thank you for doing that!
