### ISSUE TITLE
tweaking figure size

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#92]
there are several cases where figures inline are too big or margin figures are too small. here's an example from chapter 9:

<img width="1286" alt="Screen Shot 2022-09-25 at 8 14 48 AM" src="https://user-images.githubusercontent.com/1158807/192150994-1917c769-7df5-45de-9c55-4f4142232459.png">

and here's one from viz, where a key example is rendering so small we can't really appreciate it:

<img width="1374" alt="Screen Shot 2022-09-25 at 8 15 13 AM" src="https://user-images.githubusercontent.com/1158807/192151019-f6f5e945-9a3a-4524-b582-9d3126bced5c.png">

what's the best way for us to control the render size of these figures?

**Comment by mikabr** [comment]
For the second example, since it's coming from `ggplot`, the best way to control the size is using the `fig.width` and `fig.height` chunk options.

For the first example, I'm not sure which figure is too big/small? But since they're inserted with `knitr::include_graphics()`, you would use the `out.width` and `out.height` chunk options.

**Comment by mcfrank** [comment]
thanks! I think I was mixing these up and fig.width doesn't work for one, out.width doesn't work for the other. (and out.width needs to be quoted?
