### ISSUE TITLE
should we adopt TIER in project management?

### ISSUE THREAD

**Issue by mcfrank** [langcog/experimentology#97]
Seems like a good standard: https://www.projecttier.org/tier-protocol/protocol-4-0/

**Comment by TomHardwicke** [comment]
Sorry only just seen this...

I like this. Looks like its [currently designed for a copy-paste workflow rather than a dynamic documents workflow](https://www.projecttier.org/tier-protocol/protocol-4-0/#:~:text=Read%20more-,Alternative%20Workflows%3A%20Copy-and-Paste%20versus%20Dynamic%20Documents,-The%20TIER%20Protocol). But I think to adapt to a dynamic documents workflow would only require that the master script be the same as the report doc right? Though I think there could be different schools of thought on whether its best to have your analysis code in separate files that you run from the master/report doc or whether you just have that code directly in the master/report doc. The former is perhaps neater for the researcher and the latter is perhaps easier for the reader to follow?

Note that we currently recommend both the copy-paste and dynamic doc workflows, but we describe them in the "writing reproducibly" section of the writing chapter. 

So shall I start editing what we have to align with Tier?

**Comment by mcfrank** [comment]
@TomHardwicke if you wanted to make these changes as you get to the chapter, that would be awesome...

**Comment by mcfrank** [comment]
I think TIER is fine, but I'm not in love with it on a further reading. I provided a link, but didn't strongly align us.
